---
language: go
go:
- 1.15.x

cache:
  directories:
  - $GOPATH/pkg/mod

os:
- linux

install:
- curl --silent --location https://goo.gl/g1CpPX | bash -s v1.3.0

script:
- export GO111MODULE=on
- go mod download
- go mod verify
- go build ./...
