---
language: go
go:
- 1.15.x

cache:
  directories:
  - $GOPATH/pkg/mod

os:
- linux

install:
- curl --silent --location https://goo.gl/g1CpPX | bash -s v1.3.0

script:
- export GO111MODULE=on
- go mod download
- go mod verify
- go build ./...

before_deploy:
- make build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bghKYdT9Jo68GU8kL7mJQoSA8UnsoqOPLY47tcNH18rtbFp54L3USAnIpu8FRUOYLvzOrWQoZwKKAiMhN/GMYwF6uXgT5qk5l8Q8LCvjKfh3VKRZCWsCo3xPgmB9Wn3PEzTEoUa60xa98g6rp8zJ//rZJ0Ob3ceTSD113ZThUjINXafno+n2xwi7DLFOQSSAjX3TtBUW+LNkhJteTFD7Cf1dVvLapbyN3/GiT1VCLzp1rKGZ4N2e9gEXYMkG1aA0RcnlkqE6iiLwd0Rq1Y0SMKQwJ3Jc13847/CNXLRiaKg6G0hbPuAJYwRIh10QKHYueGS/zDEm6oCVwtPHUA4x3f0sWPlinoMX2VC/NXdE7ttpMwCxpAykRBB2asww9JrmIx6GVmc/ts1PrPh3RYiaAFByFijejN7vuiRJXxDACSV76FYAJ2t5G6NnB50NZWt6wcR4L+0QTURXH9Zwq5+dxCmOEXDRRUFW9Qw2oGd24MZbO2C5L/LKt1r+jE3Kf1/PTwCb+ZBpl4hChWCWGAct0arKzoLDOQuPUy19Uik45V3ViyL4JQPiQzN2DP+jnJ14G1SzEx2g6feihuk/UDYUJIXmsePnTYMo2Cp2eRcQPScrU/xLuqk6wNe0V0XOweaFzCRDnPpoktveylDWGuKI7tpxVGLoCfWb2TpMMU9PDSc=
  file_glob: true
  file: binaries/*
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.15
    tags: true
